# server setting
server:
  port: 8080


# logging
logging:
  level:
    com.innim.okkycopy: info




spring:
  # postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/okky_dev
    username: ENC(P5lAn7nJQd46rsMf5/2w5Q==)
    password: ENC(GuRfx4tqqJN9hqDCWWnDbPsIYNgxOxH3)

  # security
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(JhnSYoDaFmDwgr2OqmEvjin+Gv92pdnafb/YCY5+tg34lYz3UIiJ8tNvr9ENqkiwilVvKUXeRB9CuO90+ZnsFLcvNjXWRH8ZsGruIKSSVmbb2nT/J0sDLw==)
            client-secret: ENC(x91HIfuUF7NstcqZRUnYUNWjaAMxXB2V7xiTfPZAQ9AIipUGmlq3GPH17w9pLFkP)
            redirect-uri: https://api.okkycopy.store/login/oauth2/code/google
            scope: profile, email
          naver:
            client-id: ENC(k39tfb0pNrUMACbIwQc12T6x1ArwaVqEyfHegwrsDWQ=)
            client-secret: ENC(z6JbvfhiAWq2Ywz9CUF1ig6xNq6NHou3)
            redirect-uri: https://api.okkycopy.store/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image, nickname
            client-name: Naver
          kakao:
            client-id: ENC(5m0JpVB8P5WywsB+6mUY+bNMpKgxYno/rb+bdJZPlFxj4qGm3SYqu2S2zfmwtP3E)
            client-secret: ENC(iqj0VasRD91j7Tm09laevWLcLUuAm8CW2PPCbBXBUFBLwF9t9FFpbuKDAbOqxt+6)
            redirect-uri: https://api.okkycopy.store/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize?prompt=login
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?prompt=login

  # mail
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: okky.innim@gmail.com
    password: ENC(XKNBaO2fQd3qiHY0Y1Rix/gr4NjrlLR6y1IHK9huwZg=)
    properties.mail:
      smtp:
        auth: true
        starttls:
          enable: true
      debug: true
      mime:
        charset: UTF-8
      transport:
        protocol: smtp

  # thymeleaf
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: true
    order: 0

  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
    defer-datasource-initialization: true

  # sql
  sql:
    init:
      mode: always

# cloud
cloud:
  aws:
    s3:
      bucket: okky-copy-backend-dev
      folder-path: static/image
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      access-key: ENC(KEFZS81oj8KYeXuL3M9ikgvQk3975CgjRBE2MYvZ40w=)
      secret-key: ENC(CCtHoAQbk/a0KKLw3gRU2TRzftMXpMAsIpZCKcmF9uRzkseBcGIh+0VqU6u6TLWRrPsHg0zGuBc=)

# frontend
frontend:
  origin: https://okkycopy.store
  path:
    base: /
    signup: /oauth/signup
    mail-authenticate: /email-authenticate
    mail-change-authenticate: /email-change-authenticate