# server setting
server:
  port: 8080


# logging
logging:
  level:
    com.innim.okkycopy: debug



spring:
  # postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/okky_local
    username: for_local
    password: okky1234

  # jpa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
    defer-datasource-initialization: true

  # sql
  sql:
    init:
      mode: always