# server setting
server:
  port: 8080


# logging
logging:
  level:
    com.innim.okkycopy: info



spring:
  # postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/okky_prod
    username: for_prod
    password: okky1234

  # jpa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true

