# server setting
server:
  port: 8080


# logging
logging:
  level:
    com.innim.okkycopy: debug



spring:
  # postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/okky_local
    username: for_local
    password: okky1234

  # security
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 673990742828-f60dbpkqo1jlo185ifqf1r511hv91a5p.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email


  # jpa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
    defer-datasource-initialization: true

  # sql
  sql:
    init:
      mode: always

# cloud
cloud:
  aws:
    s3:
      bucket: okky-copy-backend-dev
      folder-path: static/image
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      access-key: AKIA43MJDZISSDPJ2I4Y
      secret-key: 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

# frontend
frontend:
  origin: http://localhost:8081
  path:
    base: /
    signup: /oauth/signup